### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_60'

### ISSUE THREAD

**Issue by NIEYALI** [CMU-Perceptual-Computing-Lab/caffe_rtpose#10]
thanks for your share, but when I ran 'install_caffe_and_cpm.sh', It has some problem, following:
NVCC src/caffe/util/im2col.cu
nvcc fatal   : Unsupported gpu architecture 'compute_60'
make: *** [.build_release/cuda/src/caffe/util/im2col.o] Error 1
make: *** Waiting for unfinished jobs....
which cudnn and cuda do you use? in my case I use cudnn4 and cuda7.5
Or do you know the problem? other way to solve it? thank you

**Comment by tsimk** [comment]
Typically cuda 8, but you can use 7.5. Try commenting the architecture flags in

https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/blob/master/Makefile.config.Ubuntu16.example#L40

The set of options commented as "#Deprecated" a few lines below should work.

**Comment by NIEYALI** [comment]
Thanks a lot
