### ISSUE TITLE
Problems when trying to execute rtpose using MPI model

### ISSUE THREAD

**Issue by marketto89** [CMU-Perceptual-Computing-Lab/caffe_rtpose#13]
Hi Everyone,

I am opening this issue because I have some problems in running rtpose using MPI model instead of COCO.

I am running the demo on an Ubuntu 14.04 machine. The demo runs fine using the COCO model.

This is what I get:
`F0125 17:44:29.373692  7559 upgrade_proto.cpp:86] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: /home/marco/workspace/caffe_rtpose/model/mpi/pose_iter_160000.caffemodel
*** Check failure stack trace: ***
    @     0x7f9b7c44cdaa  (unknown)
    @     0x7f9b7c44cce4  (unknown)
    @     0x7f9b7c44c6e6  (unknown)
    @     0x7f9b7c44f687  (unknown)
    @     0x7f9b7c990eae  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x7f9b7c9dc057  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x7f9b7c9dc0cf  caffe::Net<>::CopyTrainedLayersFrom()
    @           0x44c3d8  warmup()
    @           0x45455b  processFrame()
    @     0x7f9b7d74b184  start_thread
    @     0x7f9b7b95137d  (unknown)
    @              (nil)  (unknown)`

Am I missing something?

**Comment by gineshidalgo99** [comment]
Could you please post the whole command line you use to execute the program?

The only reason I can think of right now is that you are introducing the MPI Caffe trained model (*.caffemodel) but you are not introducing the MPI Caffe proto file.

Thanks!

**Comment by marketto89** [comment]
I just tried to remove and download the models again and now they are both working fine.

I am very sorry, I should have tried this before opening the issue.

Anyway, thank you very much for your assistance!
