### ISSUE TITLE
The number of GPUs to increase fps.

### ISSUE THREAD

**Issue by wschoi89** [CMU-Perceptual-Computing-Lab/caffe_rtpose#16]
I want to make pose recognition similar to real time. To do this, 

I used this expression below. 

--num_gpu 4 <--- Parallelize over this number of GPUs. Default is 1.

and I got this error.
F1219 15:59:41.175240 36602 common.cpp:137] Check failed: error == cudaSuccess (10 vs. 0) invalid device ordinal

I just have one graphic card, Do I have to increase the number of graphic cards to recognize the human pose in real time??

**Comment by ZheC** [comment]
We use one GTX 1080/ Titanx GPU and achieves the speed of 8~9 fps. And yes, num_gpu <= the number of graphic cards in your computer. In your case, it can not be more than one.
