### ISSUE TITLE
GPU Memory

### ISSUE THREAD

**Issue by tladyman** [CMU-Perceptual-Computing-Lab/caffe_rtpose#18]
Hi,

When running rtpose.bin I'm running out of GPU memory.

`116 syncedmem.cpp:64] Check failed: error == cudaSuccess (2 vs. 0)  out of memory`

Is there any way to decrease the amount of memory used or is the answer to use a GPU with more memory?

Cheers,
Tom

**Comment by gineshidalgo99** [comment]
Hi, we are working in a version that uses less memory (it should fit in 2GB GPUs). It will be released in around 3-5 weeks. However, if you are using a bigger GPU and it does not fit, you should reduce the number of scales and net resolution to the default values, as well as enable cuDNN. Thanks!

**Comment by ZheC** [comment]
4 Options to reduce memory usage: (1) Using MPI model instead of COCO model (2) Modifying the test.prototxt and reducing the stage number from 6 to 3. (3) Using one scale for testing  (4) Using smaller --net_resolution for testing

**Comment by madhawav** [comment]
@gineshidalgo99 Is the version for 2GB VGAs available?

**Comment by gineshidalgo99** [comment]
I am very sorry for the delay, it will be released within the next 2-3 weeks. Thank you for your patience.
