### ISSUE TITLE
rtpose.bin killed

### ISSUE THREAD

**Issue by caffelearn** [CMU-Perceptual-Computing-Lab/caffe_rtpose#19]
I have  compiled successfully,but when running rtpose.bin, if command include --video  -- write_frames, the process is killed, if   --image_dir -write_frames  ,the process is finished ,but nothing in output .why?  
is there a demo like caffe/examples/cpp_classification.cpp?

**Comment by kidapu** [comment]
Same issue happens to me.

My enviroment is following.

- Ubuntu 16.04
- cuda : 8.0
- cudnn : 5.1.1
- opencv : 3.1
- using nvidia-docker 

I exec following command, but nothing in output dir.

```
$  ./build/examples/rtpose/rtpose.bin --video ./../test.mp4 --num_gpu 2 --no_frame_drops --write_frames output/ --write_json output/ --num_scales 3 --scale_gap 0.15
init done 
opengl support available 
```

**Comment by kane777** [comment]
same here. Have you solved it yet?

**Comment by gineshidalgo99** [comment]
We do not support rt_pose any longer, please move to OpenPose:
https://github.com/CMU-Perceptual-Computing-Lab/openpose
