### ISSUE TITLE
Real time C++ code for multi-person pose estimation,when make all,it appears some problems

### ISSUE THREAD

**Issue by tanggt** [CMU-Perceptual-Computing-Lab/caffe_rtpose#2]
[platform] Ubuntu 14.04 +cuda8.0+cudnn5.1+opencv2.4.13
when I make all,it appears some problems:
1.std::runtime_error is not member of std,which could be solved by insert the header of stdexcept,then it will be make successfully!
2.After make all,when I run the command of "./build/examples/rtpose/rtpose.bin",it appear a error about threads, which is:
E1230 09:52:39.072165  3477 rtpose.cpp:1507] Finish spawning 1 threads. now waiting.
init done
opengl support available
However,then it all always waiting,no results,could anyone help me solver the problem.Thank you!

**Comment by tsimk** [comment]
1. Should be fixed by 707e1aed9f817fd4dd824afc66c35a4566c203f8
2. This is not an error, just an info message. I updated this in 53962cd48c0dd6239abe616555d136cf25731d09

As for not showing any results, I'm not sure what is happening. You may try running on an mp4 video instead, and adding the "--logtostderr" option to get more verbose logging of what is going on.

**Comment by tanggt** [comment]
I may find the key problem,which is the opencv version may be not compatible. The opencv version of mine is opencv-2.4.13.I compared it between laptop computer(opencv-2.4.9) and desktop computer(opencv-2.4.13).In laptop,the window could appear,however,the GPU memory is out.The desktop could not appear window,but using the command you suggest that could have results,which also to be add  --no_display

./build/examples/rtpose/rtpose.bin --video test.mp4 --write_frames output/ --logtostderr --no_display
I1230 19:28:11.457729 14254 rtpose.cpp:1711] Display resolution: 1280x720
I1230 19:28:11.457806 14254 rtpose.cpp:1717] Net resolution: 656x368
I1230 19:28:11.457844 14254 rtpose.cpp:1484] Finish spawning 1 threads.
I1230 19:28:11.457875 14257 rtpose.cpp:175] Setting GPU 0
I1230 19:28:11.700845 14257 rtpose.cpp:180] GPU 0: copying to person net
I1230 19:28:15.637430 14257 rtpose.cpp:202] start_scale = 1
I1230 19:28:15.637516 14257 rtpose.cpp:231] Dry running...
I1230 19:28:15.907531 14257 rtpose.cpp:233] Success.
I1230 19:28:15.907768 14257 rtpose.cpp:1081] GPU 0 is ready
I1230 19:28:21.852883 14266 rtpose.cpp:1451] # 142, NP 6, Latency 0.274, Preprocess 0.000, QueueA 0.052, GPU 0.201, QueueB 0.003, Postproc 0.008, QueueC 0.000, Buffered 0.000, QueueD 0.010, FPS = 4.1
I1230 19:28:27.976358 14266 rtpose.cpp:1451] # 263, NP 4, Latency 0.289, Preprocess 0.000, QueueA 0.068, GPU 0.201, QueueB 0.003, Postproc 0.008, QueueC 0.000, Buffered 0.000, QueueD 0.009, FPS = 4.9
I1230 19:28:34.141719 14266 rtpose.cpp:1451] # 385, NP 4, Latency 0.312, Preprocess 0.000, QueueA 0.077, GPU 0.201, QueueB 0.005, Postproc 0.009, QueueC 0.010, Buffered 0.000, QueueD 0.010, FPS = 4.9
I1230 19:28:40.354110 14266 rtpose.cpp:1451] # 509, NP 3, Latency 0.289, Preprocess 0.000, QueueA 0.067, GPU 0.200, QueueB 0.003, Postproc 0.008, QueueC 0.000, Buffered 0.000, QueueD 0.010, FPS = 4.8
I1230 19:28:45.436137 14263 rtpose.cpp:526] Done, exiting. # frames: 615

**Comment by tsimk** [comment]
* Running out of memory on a laptop might be normal, the program requires around 3GB of GPU memory. What GPUs are you using and how much memory do they have?

* Check the jpg files in output/. Do the results look reasonable? If so, then this is likely just an issue with the display.

**Comment by tanggt** [comment]
1.  Desktop computer: gtx1060 6G.
2.  I Check the jpg files in output/ and the results look reasonable. I think it has something with opencv

**Comment by gineshidalgo99** [comment]
1. If you are running out of memory with the GTX 1060, the issue might be similar to #3, and you might need to enable cuDNN on the Makefile.config. Caffe CNN uses a higher GPU memory than the cuDNN implementation.
2. Please, let us know if you were able to solve this OpenCV issue.
