### ISSUE TITLE
Video loops when write_frames disabled

### ISSUE THREAD

**Issue by makarandtapaswi** [CMU-Perceptual-Computing-Lab/caffe_rtpose#20]
If we want to just dump the JSON estimation information on a video, and not look at it (or generate images from it), the video loops after completion. It makes sense to probably check out the results on the fly and loop, but from a pre-processing or meta-data extraction point of view, maybe better to include a flag to stop looping?

This is currently ~line 540 of rtpose.cpp

**Comment by gineshidalgo99** [comment]
Thank you for your suggestion! We are working in releasing our next version in around 1 month, and we will include a flag for that. Thanks!

**Comment by yz-cnsdqz** [comment]
For temporal use, I think one can set a flag checking the end of the video stream. 
The "while(1)" loop of reading frames is in 
       examples/rtpose/rtpose.cpp: void* getFrameFromCam(void *i)
What I did is, if frame_counter decreases, then set global.quit_threads=1

**Comment by gineshidalgo99** [comment]
Thank you! We actually took a similar approach for our next version which we will release soon.
