### ISSUE TITLE
No output files with opencv 2.4.8

### ISSUE THREAD

**Issue by huzhenzhen** [CMU-Perceptual-Computing-Lab/caffe_rtpose#22]
Thank you for sharing the source code.

I have the same problem with issue [#7](https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/issues/7) with OpenCV version 2.4.8.  

`hzz@bdp-gpu-01:~/MultiPose/caffe_rtpose$ ./build/examples/rtpose/rtpose.bin --no_display --image_dir image/ --write_frames output/

E0307 17:48:00.193135 16291 rtpose.cpp:1543] rtcpm successfully finished.

E0307 17:48:00.193334 16291 rtpose.cpp:1546] Total time: 10.2573 seconds.

hzz@bdp-gpu-01:~/MultiPose/caffe_rtpose$ cd output/

hzz@bdp-gpu-01:~/MultiPose/caffe_rtpose/output$ ls

hzz@bdp-gpu-01:~/MultiPose/caffe_rtpose/output$`

I have turned off the display but there is still no output.

**Comment by scream7** [comment]
same issue

**Comment by gineshidalgo99** [comment]
Hi,
Solution on #21. (install libopencv-dev from the repository)
