### ISSUE TITLE
How to solve this error which occurs when using rtpose.bin?

### ISSUE THREAD

**Issue by yxchng** [CMU-Perceptual-Computing-Lab/caffe_rtpose#25]
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0317 17:32:11.124943 20749 solver_factory.hpp:67] Check failed: registry.count(type) == 0 (1 vs. 0) Solver type Nesterov already registered.
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by gineshidalgo99** [comment]
We do not support rt_pose any longer, please move to OpenPose:
https://github.com/CMU-Perceptual-Computing-Lab/openpose
