### ISSUE TITLE
when running live video only first frame is written to file

### ISSUE THREAD

**Issue by rguptatx** [CMU-Perceptual-Computing-Lab/caffe_rtpose#26]
i am using:
./build/examples/rtpose/rtpose.bin --camera 0 --num_gpu 1 --write_frames output13/ --write_json output13/ 
only first frame is written to file, but i see subsequent frames being processed on the screen

**Comment by yxchng** [comment]
same here

**Comment by alex-mcleod** [comment]
I think this is because the same JSON / image file keeps getting overwritten. There is some issue with the frame counter not updating properly when webcam is used.

**Comment by gineshidalgo99** [comment]
This error has been fixed in our latest release, sorry for answering that late!
https://github.com/CMU-Perceptual-Computing-Lab/openpose
