### ISSUE TITLE
rtpose.cpp compilation error

### ISSUE THREAD

**Issue by a4tunado** [CMU-Perceptual-Computing-Lab/caffe_rtpose#28]
Encountered compilation error while building rtpose.cpp.
Any help is highly appreciated.

`
examples/rtpose/rtpose.cpp: In function ‘void* processFrame(void*)’:
examples/rtpose/rtpose.cpp:1185:42: error: no match for ‘operator[]’ (operand types are ‘boost::shared_ptr<float []>’ and ‘int’)
                     frame_batch[n].joints[ij] = joints[ij];`

gcc (Ubuntu 4.9.4-2ubuntu1~12.04) 4.9.4
boost 1_49_0

**Comment by a4tunado** [comment]
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4 works fine though
looks like Ubuntu 12 is not supported

**Comment by gineshidalgo99** [comment]
It  looks like an old version of boost? Which does not have that operator implemented. This array shared pointer was included not too long ago.

**Comment by a4tunado** [comment]
Thanks! 

Probably boost version should be updated in [Dependencies.cmake](https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/blob/master/cmake/Dependencies.cmake#L5) than.

**Comment by gineshidalgo99** [comment]
Good point. Thank you for pointing it out!
