### ISSUE TITLE
How to run video or web camera from docker command line?

### ISSUE THREAD

**Issue by yao23** [CMU-Perceptual-Computing-Lab/caffe_rtpose#29]
It's much easier to use this repo from docker, but how to run video/image or web camera from docker command line?

I saw caffe training here:
https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/tree/master/docker

**Comment by gineshidalgo99** [comment]
We do not support rt_pose any longer, please move to OpenPose:
https://github.com/CMU-Perceptual-Computing-Lab/openpose
