### ISSUE TITLE
0 values in the json file; multiple skeletons in the KTH dataset

### ISSUE THREAD

**Issue by yz-cnsdqz** [CMU-Perceptual-Computing-Lab/caffe_rtpose#30]
Dear Authors,

First thank you very much for providing such a powerful tool!! It is really awesome!

However, when I estimated the skeletons in the KTH dataset, I found some inconsistencies in the generated json files. I could not fully understand why this problem happens.

For example, when I processed the video person11_handwaving_d2_uncomp.avi, in frame000156.json I got:

{
"version":0.1,
"bodies":[
{
"joints":[0,0,0,108.623,23.1522,0.252051,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,110.581,52.8297,0.351235,113.17,74.0262,0.420707,114.796,95.5481,0.566846,102.767,52.827,0.365775,104.713,73.6887,0.410267,100.82,95.221,0.55647,107.963,37.5057,0.421713]
},
{
"joints":[0,0,0,108.623,23.1522,0.252051,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,110.581,52.8297,0.351235,113.17,74.0262,0.420707,114.796,95.5481,0.566846,102.767,52.827,0.365775,104.713,73.6887,0.410267,100.82,95.221,0.55647,107.963,37.5057,0.421713]
},
{
"joints":[0,0,0,108.623,23.1522,0.252051,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,110.581,52.8297,0.351235,113.17,74.0262,0.420707,114.796,95.5481,0.566846,102.767,52.827,0.365775,104.713,73.6887,0.410267,100.82,95.221,0.55647,107.963,37.5057,0.421713]
}]
}

Here are my questions:
(1) What is the meaning of the 0 values in the "joints" entry? Do they imply detection failure?
(2) Only one person appears in the scene, so why three skeletons are generated??

I am looking forward to your answer, which are very important for my ongoing research; )

best,
Yan

**Comment by ZheC** [comment]
(1) Each joint has three values (x, y, visible flag), 0 means the joint is not detected (occluded or truncated).
(2) Could be false positive. You can actually check the result visulization.
