### ISSUE TITLE
F0406 17:19:19.386066 12837 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

### ISSUE THREAD

**Issue by cheneyfan** [CMU-Perceptual-Computing-Lab/caffe_rtpose#36]

**Comment by NHZlX** [comment]
I also meet the same problem(i use the nvidia tesla graphics with 12G memory). Have u solved it?

**Comment by gineshidalgo99** [comment]
You must use cuDNN to avoid out of memory. And If you are using it, maybe you could also reduce the batch size.

**Comment by NHZlX** [comment]
@gineshidalgo99  thanks, it works.
