### ISSUE TITLE
Check failed: error == cudaSuccess (30 vs. 0)  unknown error

### ISSUE THREAD

**Issue by garyfeng** [CMU-Perceptual-Computing-Lab/caffe_rtpose#38]
finally get everything to compile on Ubuntu 16.04/opencv3.2.0/cuda8/cudnn6, but got the following at the first run:

```
F0415 22:05:23.604416  3325 common.cpp:151] Check failed: error == cudaSuccess (30 vs. 0)  unknown error
*** Check failure stack trace: ***
    @     0x7fd156ebf2d2  google::LogMessage::Fail()
    @     0x7fd156ebf216  google::LogMessage::SendToLog()
    @     0x7fd156ebebe8  google::LogMessage::Flush()
    @     0x7fd156ec1f63  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd157764782  caffe::Caffe::SetDevice()
    @           0x40a276  warmup()
    @           0x411184  processFrame()
    @     0x7fd152af36ba  start_thread
    @     0x7fd15282982d  (unknown)
Aborted (core dumped)
```
Please help

**Comment by gineshidalgo99** [comment]
cuDNN 6 was not compatible with the old custom Caffe that we used here. We will release soon (~1-2 weeks) our new version, which is compatible with cuDNN 6. Sorry for the inconvenience!


**Updated** - the new version can be found here and it is compatible with cuDNN 6:
https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by barnoncb** [comment]
CUDA runtime error (30) might show if your program is unable to create or open the /dev/nvidia-uvm device file. This is usually fixed by installing package nvidia-modprobe:

`sudo apt-get install nvidia-modprobe`

thanks to @gheinrich
