### ISSUE TITLE
caffe failed to init()

### ISSUE THREAD

**Issue by Billfortme** [CMU-Perceptual-Computing-Lab/caffe_rtpose#39]
I am using GTX960M GPU and I compiled successfully by 
./install_caffe_and_cpm.sh

However, after the build was done , and I want to test it by typing
./build/examples/rtpose/rtpose.bin

I failed it and I didn't know what's reason yet, someone can tell me?

Thanks
Bill
The following is the hard copy of running message:

./build/examples/rtpose/rtpose.bin
F0424 10:12:09.817428  1511 cudnn.hpp:113] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
    @     0x7fb59a3855cd  google::LogMessage::Fail()
    @     0x7fb59a387433  google::LogMessage::SendToLog()
    @     0x7fb59a38515b  google::LogMessage::Flush()
    @     0x7fb59a387e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fb59aac38f8  caffe::CuDNNConvolutionLayer<>::Reshape()
    @     0x7fb59a9dad2e  caffe::Net<>::Init()
    @     0x7fb59a9dd090  caffe::Net<>::Net()
    @           0x40a608  warmup()
    @           0x411084  processFrame()
    @     0x7fb5987886ba  start_thread
    @     0x7fb5984be82d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by gineshidalgo99** [comment]
Have you install cuDNN in your system? Which version of cuDNN? (this old Caffe version is not compatible with cuDNN 6). #38

**Comment by Billfortme** [comment]
I installed CUDA 8.0 and cuDNN 6.0
Which version of CUDA and cuDNN should be ok for this project?

**Comment by gineshidalgo99** [comment]
- CUDA 8 is fine.
- cuDNN 4.X or 5.X should be fine, I use 5.1. We will release a version compatible with cuDNN 6 in around 1-4 weeks. Thanks!
