### ISSUE TITLE
different implemention of gpu and cpu version of nms_layer

### ISSUE THREAD

**Issue by KongCDY** [CMU-Perceptual-Computing-Lab/caffe_rtpose#4]
i found that the implemention of cpu and gpu forward function of nms_layer is different

**Comment by tsimk** [comment]
Yes, we don't really use the CPU implementations so they are in need of debugging. There's currently a bug where it doesn't check that peakCount doesn't exceed max_peaks. 

We'd be interested in knowing if you end up using the CPU version.

**Comment by KongCDY** [comment]
I just see how nms_layer implement, so I check the cpu implementation, the implementation is different from the result output of net, so I check the gpu implementation.
