### ISSUE TITLE
Error while running on a video

### ISSUE THREAD

**Issue by tchinchuthomas** [CMU-Perceptual-Computing-Lab/caffe_rtpose#40]
Hi,

I am getting the following error while testing it with video. Please help.

F0427 11:36:23.180558  8473 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7f8f2bad15cd  google::LogMessage::Fail()
    @     0x7f8f2bad3433  google::LogMessage::SendToLog()
    @     0x7f8f2bad115b  google::LogMessage::Flush()
    @     0x7f8f2bad3e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8f2f88cf40  caffe::SyncedMemory::to_gpu()
    @     0x7f8f2f88bf29  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7f8f2f88e382  caffe::Blob<>::mutable_gpu_data()
    @     0x7f8f2f7a79b8  caffe::BaseConvolutionLayer<>::forward_gpu_gemm()
    @     0x7f8f2f93f796  caffe::ConvolutionLayer<>::Forward_gpu()
    @     0x7f8f2f8788e2  caffe::Net<>::ForwardFromTo()
    @           0x40a81b  warmup()
    @           0x411204  processFrame()
    @     0x7f8f2a9d26ba  start_thread
    @     0x7f8f2a70882d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by ZheC** [comment]
As the error message states: error == cudaSuccess (2 vs. 0) **out of memory**. How many GBs GPU memory does your computer have?

**Comment by tchinchuthomas** [comment]
It has 2 GPUs (Nvidia GTX 1080 )each of 8GB  GPU memory, 32 CPU core, 64 GB RAM. Unable to understand why is it still out of memory despite having good  GPU resources. By any case, are these resources still insufficient to run the code?

**Comment by tsimk** [comment]
That's sufficient---we've used similar setups. Looks like you're not using cuDNN, you must use it to avoid this issue, e.g., https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/issues/36
