### ISSUE TITLE
Working on 2GB VGA and 8GB RAM

### ISSUE THREAD

**Issue by madhawav** [CMU-Perceptual-Computing-Lab/caffe_rtpose#41]
Is it possible to make this project workable on specs specified in title?
I have read at [1] that their will be a version released for 2GB VGAs. When will it be released?
[1] - https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/issues/18#issuecomment-280345184

**Comment by gineshidalgo99** [comment]
I am very sorry for the delay, it will be released within the next 2-3 weeks. Thank you for your patience.

Check the new GitHub repo: https://github.com/CMU-Perceptual-Computing-Lab/openpose

**Comment by madhawav** [comment]
@gineshidalgo99 any updates on this release? Eagerly looking forward for it.
Thanks

**Comment by ZheC** [comment]
Please check the new github repo: https://github.com/CMU-Perceptual-Computing-Lab/openpose
