### ISSUE TITLE
Can I know why 16 * ceil(NET_RESOLUTION_WIDTH * scale /16)? 

### ISSUE THREAD

**Issue by yxchng** [CMU-Perceptual-Computing-Lab/caffe_rtpose#43]
Isn't multiplying by 16 and dividing by 16 equal to not doing anything?

**Comment by gineshidalgo99** [comment]
Yes, multiplying by 16 and dividing by 16 equal to not doing anything

But this is the opposite, dividing by 16 and multiplying by 16 is NOT equal to doing nothing. At least not if it's an int.
15 / 16 * 16 = 0
17 / 16 * 16 = 16
33 / 16 * 16 = 32

Anyway, i'd highly recommend to move to OpenPose
https://github.com/CMU-Perceptual-Computing-Lab/openpose
