### ISSUE TITLE
 CMakeLists.txt for caffe_rtpose examples

### ISSUE THREAD

**Issue by suprunai** [CMU-Perceptual-Computing-Lab/caffe_rtpose#45]
Please help me!
>>CMake Error at CMakeLists.txt:74 (add_subdirectory):
>>The source directory
>>D:/openpose/caffe_rtpose-master/examples
>>does not contain a CMakeLists.txt file.

**Comment by gineshidalgo99** [comment]
There is no CMake ready for rt_pose, you will have to use the normal Makefile installation mode, sorry.

You might really consider to move to the new faster and more accurate library: https://github.com/CMU-Perceptual-Computing-Lab/openpose (there is no CMake in the new one yet, but we are planning to it in the future)

**Comment by suprunai** [comment]
Thank you! Is it possible to build rt_pose for Windows? I need CPU_Only..

**Comment by gineshidalgo99** [comment]
There is no CPU version, i am sorry. There is Windows version in OpenPose though.
