### ISSUE TITLE
Some videos are aborted while processing pose machines on them

### ISSUE THREAD

**Issue by srijandas07** [CMU-Perceptual-Computing-Lab/caffe_rtpose#47]
The error is like 
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
pure virtual method called
terminate called recursively

**Comment by suishii** [comment]
Did you solve this problems? If you did, could you tell me? Thank you.

**Comment by srijandas07** [comment]
What I found is that, its a mutex warning and does not affects your results in any way. So you can continue with that. Even you can try to reduce your scales to avoid this exception. Let me know.

**Comment by gineshidalgo99** [comment]
Please, move to the updated, faster and more accurate https://github.com/CMU-Perceptual-Computing-Lab/openpose

Thanks!
