### ISSUE TITLE
cudnn v6 not supported

### ISSUE THREAD

**Issue by zhezh** [CMU-Perceptual-Computing-Lab/caffe_rtpose#48]
Recently, tensorflow 1.3 has updated to cudnn 6, so I updated cudnn to 6.

As I exec`./install_caffe_and_cpm.sh`, there are compiling error with `./include/caffe/util/cudnn.hpp`.

For a few time trying, I find the newest caffe has different version `cudnn.hpp`.

Then I replace this hpp file with the newest one, it works fine.

**Comment by gineshidalgo99** [comment]
Hi, we are not maintaining this repository anymore. Please, use OpenPose which supports cuDNN 6 and 7. Thanks!
