### ISSUE TITLE
output frame count inconsistent with the input directory

### ISSUE THREAD

**Issue by iammarvelous** [CMU-Perceptual-Computing-Lab/caffe_rtpose#49]
In my testing, I found that for some image folders, rtpose.bin generate the exactly the same number of json files as that of image files in the source image folder. However, for some image folders, it doest not have the last two frame jsons. Is this behaviour as expected?
```
$ ls output_frame | tail
003496.jpg
003497.jpg
003498.jpg
003499.jpg
003500.jpg
003501.jpg
003502.jpg
003503.jpg
003504.jpg
003505.jpg
$ ls input_frame | tail
003498.jpg
003499.jpg
003500.jpg
003501.jpg
003502.jpg
003503.jpg
003504.jpg
003505.jpg
003506.jpg
003507.jpg
```

**Comment by gineshidalgo99** [comment]
Not maintained anymore, use the newer version https://github.com/CMU-Perceptual-Computing-Lab/openpose/, it has much more functionality
