### ISSUE TITLE
When make all successfully, it appear no results and causes the system to crash

### ISSUE THREAD

**Issue by tanggt** [CMU-Perceptual-Computing-Lab/caffe_rtpose#5]
[platform]Ubuntu 14.04+cuda8.0 +gtx1060 6G
when I excute  the command of rtpose.bin , show infomation as follows:
forever@GoogleMind:~/caffe_demo-master$ ./build/examples/rtpose/rtpose.bin --video test.mp4 --logtostderr

I1230 17:57:56.720556 11047 rtpose.cpp:1711] Display resolution: 1280x720
I1230 17:57:56.720675 11047 rtpose.cpp:1717] Net resolution: 656x368
I1230 17:57:56.720731 11047 rtpose.cpp:1484] Finish spawning 1 threads.
I1230 17:57:56.720790 11050 rtpose.cpp:175] Setting GPU 0
init done 
opengl support available 
I1230 17:57:56.964375 11050 rtpose.cpp:180] GPU 0: copying to person net
I1230 17:58:00.892221 11050 rtpose.cpp:202] start_scale = 1
I1230 17:58:00.892299 11050 rtpose.cpp:231] Dry running...
I1230 17:58:01.170068 11050 rtpose.cpp:233] Success.
I1230 17:58:01.170305 11050 rtpose.cpp:1081] GPU 0 is ready
I1230 17:58:30.679666 11062 rtpose.cpp:540] Looping video after 615 frames
I1230 17:59:04.849298 11062 rtpose.cpp:540] Looping video after 615 frames
I1230 17:59:39.570911 11062 rtpose.cpp:540] Looping video after 615 frames

After 10 minutes,this program causes the system to crash.
I could understand why?

**Comment by ZheC** [comment]
Please report the follow-up problem in the same issue you opened before: https://github.com/CMU-Perceptual-Computing-Lab/caffe_demo/issues/2

From the information you provided, it seems that the code has processed all the frames from the video but it did not display the result. Could you add the output option to save the result and see? 
mkdir output
./build/examples/rtpose/rtpose.bin --video test.mp4 --write_frames output/

**Comment by handale88** [comment]
I also have the same problem. In my case, After the message 'GPU0 is ready', program causes the system to crash in 2 minutes...
When I just use the webcam, the system crashes within 2 minutes as well..
Please help me out.

**Comment by ZheC** [comment]
It is openCV version issue as reported in https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/issues/2, we are using openCV 2.4.9

**Comment by tanggt** [comment]
@handale88  read the issue as reported in #2
