### ISSUE TITLE
How can I find the information about the joints in the code?

### ISSUE THREAD

**Issue by shootingliu** [CMU-Perceptual-Computing-Lab/caffe_rtpose#51]
I am not familiar with C++，and I want to get the information  that has been detected(about the joints) to do something in realtime detection. I know the '--write_json',and I want to know where is the **# code** to   implement this instruction.

Thanks a lot.

**Comment by gineshidalgo99** [comment]
Repo not maintained anymore. Please, use https://github.com/CMU-Perceptual-Computing-Lab/openpose/ instead
