### ISSUE TITLE
memory issue when cudnn is found

### ISSUE THREAD

**Issue by Gjain234** [CMU-Perceptual-Computing-Lab/caffe_rtpose#54]
I've looked through the older issues but still can't seem to figure this out. I am trying to install openpose and am fairly sure I am using CUDNN because making on CMake gives this summary.

-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 8.0
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_50
-- Found cuDNN: ver. 5.1.10 found (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Found gflags (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe will be downloaded from source now. NOTE: This process might take several minutes depending
on your internet connection.
-- Caffe has already been downloaded.

However, when I build openpose using 'make -j`nproc`',  the caffe configuration summary shows  this:

 General:
--   Version           :   1.0.0
--   Git               :   1.0-112-g9453eb0-dirty
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   OFF
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   OFF
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   OFF
--   USE_LEVELDB       :   OFF
--   USE_LMDB          :   OFF
--   USE_NCCL          :   OFF
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.58)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.6.1)
--   CUDA              :   Yes (ver. 8.0)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_50
--   cuDNN             :   Not found
-- 
-- Install:
--   Install path      :   /home/il/software/openpose/build/caffe

This summary seems to say that cuDNN was not found, and  I get the same failure message (Check failed: error == cudaSuccess (2 vs. 0) out of memory) when I run any of the commands in the openpose quickstart section. Any ideas why there is the discrepancy about the cudnn being found?

**Comment by gineshidalgo99** [comment]
Use OpenPose, this repo is no longer maintained
